name: Maven Build and Store Artifact

on:
  push:
    branches:
      - SUB

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
      
    - name: Build with Maven
      run: mvn clean package -B
      
    - name: Copy WAR artifact to staging directory
      run: mkdir staging && cp target/*.war staging
      
    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: staging
